[workspace]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "url"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test-url = "mojo run test_url.mojo"
format = "mblack url.mojo test_url.mojo"

[dependencies]
mojo = ">=1.0.0b1"
